### ISSUE TITLE
Zuul tests fail when using multiple sockets

### ISSUE THREAD

**Issue by kevin-roark** [Automattic/socket.io-client#620]
Currently mocha tests using zuul have to use the same global socket -- if each test uses a separate socket, only the first test passes and every other test fails, regardless of the test.

It is probably related to multiplexing and the single socket being closed. It is also probably socket.io level because engine.io browser tests use individual sockets and work fine.

**Comment by rase-** [comment]
This doesn't seem to be the case anymore.
