### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by utan** [Automattic/socket.io-client#641]
XMLHttpRequest cannot load http://domain.com:8080/socket.io/?EIO=2&transport=polling&sid=z1N_9JpKElJJ6b2qAAAL. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://domain.com' is therefore not allowed access. 
server:
<pre>
<code>var server = require('http').Server();
var io = require('socket.io')(server);
io.on('connection', function(socket){
  socket.on('test', function(data){});
  socket.on('event', function(data){});
  socket.on('disconnect', function(){});
});
server.listen(8080);</code></pre>

client:
	<pre><code>[/script  src="http://domain.com:8080/socket.io/socket.io.js"][/script]
		var socket = io.connect('http://domain.com:8080');
		socket.on('connect', function(){
			socket.emit( 'test' , { test : 'right' });// if use right on connect , errors out
			socket.on('event', function(data){});
			socket.on('disconnect', function(){});
		});
</code></pre>

Can anyone replicate this issue? browser giving error is Chrome, in Firefox just loops..
I think is because when connect and you try to send an emit right away , the client is upgrading connection and fired the emit every time..

It just an assumption , one with better acknowledge could give some more info..

Same test was done with previous repository ver 1.. and it doesn't have same behavior.

**Comment by erupenkman** [comment]
is this still an issue? I experienced it with 1.x but after upgrading to 1.2.1 no longer experience it

**Comment by marcog83** [comment]
Same bug with socket.io 1.2.1 I downgrade to 0.9.17 and it works

**Comment by rauchg** [comment]
@marcog83 can you describe your test case and include the `DEBUG=*` and `localStorage.debug='*'` output?

**Comment by marcog83** [comment]
Hi @rauchg,
well... not sure what you meant about DEBUG=* localStorage.debug='*' I try to explain :)

socket.io library is compressed with r.js 

    "socket.io": "./bower_components/socket.io-client/dist/socket.io"

and final libraries.min.js is served in http://mydomain.local/js/libs/libraries.min.js

my site runs with xampp  on http://mydomain.local/
my server script runs    on http://mydomain.local:2503/

attached image is server script
![socket io](https://cloud.githubusercontent.com/assets/4071265/5708277/ef84aa44-9a8f-11e4-96da-519b67b7a5ae.jpg)


While i'm writing a doubt is raising... Is it a valid code? maybe some API are different :\

**Comment by rauchg** [comment]
@marcog83 there's an easy way to share everything that happened at a low level on both browser and server. More information here: http://socket.io/docs/logging-and-debugging/

**Comment by rauchg** [comment]
(that helps socket.io devs figure out the issue faster)

**Comment by marcog83** [comment]
Ok, i'll check it tomorrow, (italian timezone).

**Comment by Abramovick** [comment]
Having the same problem too with version 1.2.1. Am gonna try downgrading now.

**Comment by rogierschouten** [comment]
Getting this error after upgrading to socket.io 1.3.2.  Not having this problem with 1.1.0
Node version is 10.0.36

I'm connecting like this on the client side:
```javascript
this._socket = io.connect("/" + namespace);
```

Error message:
```
XMLHttpRequest cannot load http://127.0.0.1/socket.io/?EIO=3&transport=polling&t=1422528892484-0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8004' is therefore not allowed access. The response had HTTP status code 500.
```

I don't understand what it's doing on 127.0.0.1 without the 8004 port as I'm browsing to http://127.0.0.1:8004

**Comment by rogierschouten** [comment]
I suspect this piece of new code in commit ea9b2b72ad989dd0a4df420973a33f33a53dbc77
in file socket.io.js line 1580:

```javascript
   if (opts.host) {
     var pieces = opts.host.split(':');
     opts.hostname = pieces.shift();
-    if (pieces.length) opts.port = pieces.pop();
+    if (pieces.length) {
+      opts.port = pieces.pop();
+    } else if (!opts.port) {
+      // if no port is specified manually, use the protocol default
+      opts.port = this.secure ? '443' : '80';
+    }
   }
 ```

It seems that for a relative path  (like my io.connect("/" + namespace) above)  it would set a port of 443 or 80 and override the original port.

**Comment by leszekhanusz** [comment]
Strange with socket.io 0.9.x I had this code on the frontend to connect locally (on port 9000):

``` javascript
    var socket = io.connect('http://localhost');
```

and it was working fine (socket.io was detecting the port somehow ?)
After updating to 1.3.2, I receive these CORS error messages (because apache is running on port 80 and now socket.io is trying port to connect on port 80).

Simply changing the connection method to this solved my problem:
``` javascript
    var socket = io.connect('http://localhost:9000');
```

**Comment by defunctzombie** [comment]
@leszekhanusz The page with that javascript snippet to connect to the socket.io server, is that being accessed in a browser with http://localhost or http://localhost:9000 ?

From your post it seems like you have the site running behind apache and thus open the url http://localhost to access the website and js resources. Could you please clarify.

**Comment by leszekhanusz** [comment]
@defunctzombie 
My apache server has nothing to do with the node.js (and socket.io) code

I am using http://localhost:9000 in the browser to access the node.js page

Sorry if I was not clear.

**Comment by defunctzombie** [comment]
@leszekhanusz thanks

Let me explain the issue a bit more. The problem with using the window port when you have specified a full path like that is when you want to connect to servers on other ports. Lets say instead of localhost, I wanted to use http://socketio.some-server.com as my connection endpoint. If we blindly take the port from the `location` then it becomes impossible to do this when the page is hosted on `localhost:9000` or some other location during testing.

I believe the correct fix for you and others seeing this is to use `/` as the connection url when you want to connect to the same server that served the page. The issue is that by specifying an absolutely full URL, the url parser reads it as such and thinks that you want to connect to `http://localhost` which is port 80 since http is port 80.

I would make the strong argument that the new behavior is the correct behavior and that previous behavior was broken. Maybe we can do something for localhost, but again we run into the same problem that if I don't specify the port, the browser *should* be trying on the default protocol port.

**Comment by rogierschouten** [comment]
@defunctzombie  thanks for the explanation. But I AM connecting using "/". Therefore I think the implementation is broken at this time. socket.io decides on its own to stop using the port number of the original URL.

**Comment by ezmiller** [comment]
I'm also getting this issue with socket.io v1.3.2. I'm a newbie to socket.io so there could be something that I'm doing wrong. The code is very simple. It's just meant to be a test for socket.io so I can familiarize myself with it. I have a file `app.js`: 

```
var app = require('http').createServer(handler)
	, io = require('socket.io').listen(app)
	, fs = require('fs');

app.listen(3000);

function handler (req, res) {
	fs.readFile('index.html', function (err, data) {
		if ( err ) {
			res.writeHead(500);
			return res.end('Error loading index.html');
		}
		res.writeHead(200);
		res.end(data);
	});
}

io.sockets.on('connection', function (socket) {
	socket.emit('news', { hello: 'world'} );
});
```

And a file `index.html`: 

```
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
</head>
<body>
	<h1>Socket Test</h1>
	<script src="/socket.io/socket.io.js"></script>
	<script>
		var socket = io.connect('http://localhost');
		socket.on('news', function (data) {
			console.log(data);
		});
	</script>

</body>
</html>
```

In the console, I get the following error:

> GET http://localhost/socket.io/?EIO=3&transport=polling&t=1422781889267-65 
(index):1 XMLHttpRequest cannot load http://localhost/socket.io/?EIO=3&transport=polling&t=1422781889267-65. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404.

**Comment by utan** [comment]
@ezmiller, 
You should add <code>var socket = io.connect('http://localhost:3000');</code>  to your code.. unless you set ur Node Server with port 80.

**Comment by ezmiller** [comment]
Thanks @utan . That was it.

**Comment by irisSchaffer** [comment]
Just to add another detail to this issue:

I had the same problem, when I was trying to establish a connection between different servers with  `path` set to `'/socket.io-client'`. Although including the script `<script src="socket.io-client/socket.io.js"></script>` locally worked, accessing the same script from another server failed.

Removing the `path` option solved the issue for me.

**Comment by Nekle** [comment]
Change
```
var socket = io.connect('http://localhost:3000');
```
to
```
var socket = io.connect();
```
Solve this issue

**Comment by falafflepotatoe** [comment]
@neckle using client side: `io.connect('localhost:port')` worked for me.

it should be `ws://url` or name:port

also i had to DL the socket.io.js script from the downloads page cdnjs.com link, the engine-io.js repository script linked is not working.

also client side
    var socket = io(url)
    socket.on('connect', function() { ... })

doesnt work, its too fast. `socket = io(url).on('connect, function(){..})`... works.

**Comment by djay1988** [comment]
This works for me

app = express();
app.get(/^socket.io.js$/, function(req, res) {

    res.setHeader('Access-Control-Allow-Origin', 'TRUE');
    // Request headers you wish to allow
    res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');

    res.sendfile('socket.io.js');

});

and script file
`<script src="http://{YOUR Domain}:{PORT}/socket.io/socket.io.js"></script>`

**Comment by BrentMShanahan** [comment]
I was just running into this issue with version 1.4.5. I tried most of the stuff detailed here with no luck. What ended up fixing it was implementing the server side like this (reference from SO: [Here](http://stackoverflow.com/questions/25187551/socket-io-polling-404-in-laravel) );

Change the creation of io from:

`var express = require('express');`
`var app     = express();`
`var http    = require("http").Server(app);`
`var io      = require("socket.io")(http);`

To:

`var socket = require('socket.io');`
`var express = require('express');`
`var http = require('http');`

`var app = express();`
`var server = http.createServer(app);`

`var io = socket.listen(server);`

Client:

`var socket = io.connect('http://localhost:{PORT}');`
 `this.socket.on('connect', function(){`
      `console.log('Socket.io Connected')`
 `});`

HTML:
`<script src="http://localhost:3030/socket.io/socket.io.js"></script>`

**Comment by x343734282** [comment]
the same issue here
client 1.4.8

**Comment by wecole** [comment]
if you are using PHP just include **_header('Access-Control-Allow-Origin: *');_** in the server side script.It will solve the problem

**Comment by hiedwincp** [comment]
Please use @CrossOrigin on the backendside in Spring boot controller (either class level or method level) as the solution for Chrome error'No 'Access-Control-Allow-Origin' header is present on the requested resource.'

This solution is working for me 100% ...

> Example : Class level

@CrossOrigin
@Controller
public class UploadController {

----- OR -------

> Example : Method level

@CrossOrigin(origins = "http://localhost:3000", maxAge = 3600)
@RequestMapping(value = "/loadAllCars")
    @ResponseBody
    public List<Car> loadAllCars() {


Ref: https://spring.io/blog/2015/06/08/cors-support-in-spring-framework

**Comment by tbenyon** [comment]
Abdul22 fixed my bug! https://github.com/socketio/socket.io-client/issues/641#issuecomment-60749328

**Comment by congnghia0609** [comment]
I using code client following, run good:

//Client:
`var connectionOptions =  {
            "force new connection" : true,
            "reconnectionAttempts": "Infinity", //avoid having user reconnect manually in order to prevent dead clients after a server restart
            "timeout" : 10000,                  //before connect_error and connect_timeout are emitted.
            "transports" : ["websocket"]
        };
        
        var socket = io('yourdomain.com', connectionOptions);`

Wish code fun :)

**Comment by jwulf** [comment]
I had my socket.io connections start to fail after adding service worker pre-caching to my app. It might be because the client-side socket.io was loading out of cache rather than over the network. I added the connectionOptions above and did a hard refresh of the app, and it started it working.

**Comment by JinnaBalu** [comment]
this extension in chrome resolved my issue 
https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en

**Comment by ikuriel** [comment]
i fixed the message of headers in NodeJS/Express with this:

```	
response.header('Access-Control-Allow-Credentials', 'true');
response.header('Access-Control-Allow-Origin', request.get('origin'));
```

but still getting a:

> zone.js:2622 GET http://localhost:PORT/socket.io/?EIO=3&transport=polling&t=LsQEsjS 404 (Not Found)

**Comment by ikuriel** [comment]
fixed the 404 (Not Found) with this:

https://stackoverflow.com/a/27394696/2038286

because my config is for Express v4

Solved.

**Comment by BigBigWen** [comment]
the same issue here
Because  socket.io is by default, a long-polling connection is established first, then upgraded to "better" transports (like WebSocket). If you like to live dangerously, this part can be skipped:
```
const socket = io(url,{transports: ['websocket']});
```

**Comment by jionet** [comment]
what code is instead of @crossOrigin in python?
how can we integrate it in djnago?

**Comment by MuhammadMavia** [comment]
**777**### ###

**Comment by JackyChan** [comment]
the same issue here
socket.io server 2.2.0 and socket.io client 2.2.0

**Comment by Juanklg** [comment]
I have the same problem. V 2.1.1 server and client

**Comment by orange1337** [comment]
> Same problem here with version 2.2.0.
> 2.1.1 works fine.

Have the same problem. 
Than's for your reply !!

**Comment by tradingstratagem** [comment]
> > I have the same problem. socket.io server 2.2.0 and socket.io client 2.2.0
> > ![image](https://user-images.githubusercontent.com/11915449/49219037-3a744d80-f3b9-11e8-9b6b-57be1cec04a2.png)
> 
> congnghia0609's solutions worked for me (setting the connection options on the client side), after upgrading to 2.2.0 on the backend

Seems to work, thank you!

**Comment by samuelterra22** [comment]
I also updated to the latest version and added the tag **_transports_**. I did as shown [here](https://github.com/tlaverdure/laravel-echo-server/issues/162#issuecomment-415830727)

**Comment by craigcosmo** [comment]
> I using code client following, run good:
> 
> //Client:
> 
> ```
> var connectionOptions =  {
>             "force new connection" : true,
>             "reconnectionAttempts": "Infinity", //avoid having user reconnect manually in order to prevent dead clients after a server restart
>             "timeout" : 10000,                  //before connect_error and connect_timeout are emitted.
>             "transports" : ["websocket"]
>         };
>         
>         var socket = io('yourdomain.com', connectionOptions);
> ```
> 
> Wish code fun :)

this solution works. thank you so much

**Comment by darrachequesne** [comment]
For future readers:

Using `transports: ["websocket"]` simply disables HTTP long-polling, which may or may not be what you really want (but it works, since there's no CORS for WebSockets)

Response for Socket.IO v2: the library should automatically add the necessary headers

You can use the `origins` option to provide a list of authorized domains (all are authorized by default):

```js
const io = require("socket.io")(httpServer, {
  origins: ["https://example.com"]
});
```

For custom headers/sending cookies (withCredentials), you can use the `handlePreflightRequest` method:

```js
const io = require("socket.io")(httpServer, {
  origins: ["https://example.com"],

  // optional, useful for custom headers
  handlePreflightRequest: (req, res) => {
    res.writeHead(200, {
      "Access-Control-Allow-Origin": "https://example.com",
      "Access-Control-Allow-Methods": "GET,POST",
      "Access-Control-Allow-Headers": "my-custom-header",
      "Access-Control-Allow-Credentials": true
    });
    res.end();
  }
});
```

For Socket.IO v3: you must now explicitly enable CORS:

```js
const io = require("socket.io")(httpServer, {
  cors: {
    origin: "https://example.com",
    methods: ["GET", "POST"],
    allowedHeaders: ["my-custom-header"],
    credentials: true
  }
});
```

If you still get a `No 'Access-Control-Allow-Origin' header is present on the requested resource.` error message, it might mean that you are not reaching the Socket.IO server. This can be tested with:

`curl -X GET https://example.com/socket.io/?EIO=3&transport=polling` which should return a JSON (the Engine.IO handshake)

**Comment by lhermann** [comment]
Thank you so much @darrachequesne for summing it up. Works perfectly!

**Comment by prettyirrelevant** [comment]
thanks @darrachequesne. I feel this would be a nice addition to the docs, maybe like a note.

**Comment by darrachequesne** [comment]
@prettyirrelevant you are absolutely right :+1: 

Doc for v2: https://socket.io/docs/v2/handling-cors/
Doc for v3: https://socket.io/docs/v3/handling-cors/

**Comment by bashiru98** [comment]
i also had the same issue so i just added this in package.json => {"proxy":"backend url"} and in where am using socketio i called 
the enpoint as endpoint='/' and it worked fine

**Comment by DeividasV** [comment]
> For Socket.IO v3: you must now explicitly enable CORS:

this is exactly what was the problem i my case. spent few hours trying to figure out. thanks

**Comment by stempest0925** [comment]
The version I used was 3.0.4, and this error also occurred. Many methods were used. The modification according to the official cors had no effect. Finally, the transports were added to the client to run successfully.

`io("http://localhost:3000", { transports: ["websocket"] });`

**Comment by hellosurbhi** [comment]
> ``

This worked for me! I'm using version 3.0.4 of socket as well 
Thanks @stempest0925

**Comment by hellosurbhi** [comment]
> `io("http://localhost:3000", { transports: ["websocket"] });`

This worked for me! I'm using version 3.0.4 of socket as well
Thanks @stempest0925

**Comment by darrachequesne** [comment]
> The modification according to the official cors had no effect.

Could you please explain? Please see the example here: https://github.com/socketio/socket.io-fiddle/tree/cors

Note: disabling HTTP polling (with `transports: ["websocket"]`) is indeed a solution, though that means that there is no fallback if the websocket connection cannot be established.

**Comment by imvickykumar999** [comment]
> Issue for me, as well. I want to emit immediately after connection, which is before the transport is upgraded from XHR Polling.
> 
> Instructing the client to use the "websocket" transport first might help mitigate the issue, but it still won't help users in browsers that don't support websockets.
> 
> `var socket = io('http://localhost', {transports: ['websocket', 'polling', 'flashsocket']});`
> 
> engine.io-client XHR transport really needs CORS support.

.....would 'http://localhost' be valid for the deployed site on Heroku ??

**Comment by jgalvan031986** [comment]
Volvi a la version 2.3.0 y funciono a la primera.

**Comment by darrachequesne** [comment]
I'm locking the thread, as I feel there's nothing more we can do to help. Please check the documentation here:

- Socket.IO v2: https://socket.io/docs/v2/handling-cors/
- Socket.IO v3: https://socket.io/docs/v3/handling-cors/
