### ISSUE TITLE
Second connect to disconnected host fails without 'forceNew: true'

### ISSUE THREAD

**Issue by bazineta** [Automattic/socket.io-client#654]
We have a single-page app.  One view in the app is a realtime dashboard, and uses socket.io for push notifications; the other views are not realtime and thus don't use it.

When the code for the dashboard view loads, it connects to the socket.io server.  This works fine.

When the user transitions away from the dashboard view, we call socket.disconnect().  The socket disconnects correctly.

Upon transition back to the dashboard view, subsequent connect operations hang unless {forceNew: true} is passed.

While the force works around the situation, I'm confused as to why it's needed.  We disconnected the socket; why would subsequent connect() calls be attempting to use a cached underlying implementation that's been disconnected?

**Comment by rase-** [comment]
Manual reconnection works without having to re-register listeners after https://github.com/Automattic/socket.io-client/commit/a0f63d740807acf895080136464792a980b5b35b
