### ISSUE TITLE
About socket constructor via ioc manager

### ISSUE THREAD

**Issue by luckyan315** [Automattic/socket.io-client#663]
In `sio-pre2` / `ioc-pre2`, It seemed i have to pass the namespace twice as create the socket obj via ioc manager
```javascript
    var mgr = ioc.Manager(address + '/user');
    var user_socket = mgr.socket('/user');
    user_socket.on('connect', function(){
      done();
    });

```
and  if user do not pass the ns , socket.io:client throw errors...
```javascript
var mgr = ioc.Manager(address + '/user');
    var user_socket = mgr.socket();
    user_socket.on('connect', function(){
      done();
    });
```

```javascript
TypeError: Cannot call method 'forEach' of undefined
    at /Users/angl/code/github/chat/node_modules/socket.io/lib/client.js:73:26
    at /Users/angl/code/github/chat/node_modules/socket.io/lib/namespace.js:168:17
```

**Comment by rase-** [comment]
You shouldn't need to specify the namespace twice. The `Manager` shouldn't need the namespace, but instantiating a socket does. This test provides an example: https://github.com/Automattic/socket.io-client/blob/master/test/connection.js#L235
