### ISSUE TITLE
Duplicate fire of reconnect_failed event

### ISSUE THREAD

**Issue by ismarslomic** [Automattic/socket.io-client#705]
It seems like reconnect_failed event is fired twice. I have tried setting different values for reconnectionAttempts, but even if it is 1, 2 or 3 it always fire the event twice.

To reproduce scenario, run

    var opts = { reconnection: true, reconnectionAttempts: 3, reconnectionDelay: 500}
    var socket = io.connect(opts)
    socket.on('reconnect_failed', function() {
        console.log("Reconnect failed")
    })

While running kill node server (CTRL+C) and you will get following output in Developer tools console:

    Reconnect failed
    Reconnect failed 

Im using socket.io 1.0.5

**Comment by rase-** [comment]
Fixed in https://github.com/Automattic/socket.io-client/pull/708
