### ISSUE TITLE
disconnect from namespace

### ISSUE THREAD

**Issue by redannick** [Automattic/socket.io-client#724]
If I disconnect a client that was connected to the global namespace it disconnects as I'd expect. However if I've connected to a custom namespace and disconnect the client, it keeps trying to reconnect, keeping my test script from completing properly. 

Is this expected behaviour? It doesn't seem correct to me.

**Comment by rase-** [comment]
It shouldn't be trying to reconnect after an explicit reconnect. Does this still happen with the current version? There have been some reconnection fixes in the couple previous version.
