### ISSUE TITLE
Latest build is missing engine.io-client changes

### ISSUE THREAD

**Issue by johanneswuerbach** [Automattic/socket.io-client#801]
It seems that the latest build is missing some engine.io-client changes like: https://github.com/Automattic/engine.io-client/blob/master/engine.io.js#L2810

When I try to run `make socket.io.js` I get `make: `socket.io.js' is up to date.`, but when I remove the `socket.io.js` manually and rebuild it, I see all missing changes.

//cc @rauchg

**Comment by rauchg** [comment]
`1.3.2` includes the right build. Thanks!

**Comment by rauchg** [comment]
We're gonna automate the installing + building + tagging + syncing versions between repos + CDN for `1.4`

**Comment by johanneswuerbach** [comment]
Great, I was just waiting for this specific change to be released (required for testem) and wondered why it was missing.
