### ISSUE TITLE
Error parsing handshake when socket.io server only responds to /socket.io/1 requests

### ISSUE THREAD

**Issue by robertoandrade** [Automattic/socket.io-client#810]
I get errors when trying to connect to a socket.IO backend because it seems like the client is defaulting to performing the xhr request to `/socket.io` which always answers with `Welcome to socket.io` on my setup unless the request is made to `/socket.io/1`. The error wasn't very intuitive either as I had to drill down to the `engine.io-client` to figure out that that was the response I was getting from the server and that the client was defaulting the request to the wrong path.

Is there anything that can be done to make this an easier/clearer issue to troubleshoot?

**Comment by nkzawa** [comment]
I think this never happens when socket.io server and client have same version. How do you install them?

**Comment by robertoandrade** [comment]
I was using 1.3.2 client, and given the target server only responds to `/socket.io/1` I'm supposing it's a `1.x+` server.

**Comment by nkzawa** [comment]
I guess you are using 0.9.x for the server since the message "welcome to socket.io" doesn't exist on 1.x.x.

**Comment by robertoandrade** [comment]
hum... is it usual to have an 0.9.x install only respond to `/socket.io/1`?

**Comment by nkzawa** [comment]
Yeah I think so. Anyway please check your server version. I believe this is not the problem of socket.io.

**Comment by robertoandrade** [comment]
ok, tried with `0.9.17` and it worked ok, so I guess that was it. Thanks for the help.
