### ISSUE TITLE
memory leaks on windows clients in V1.3.3, V1.2.1

### ISSUE THREAD

**Issue by jollek** [Automattic/socket.io-client#816]
Have an app that sends permanent data to more than ten windows clients so users can choose what they need. This app should run 24/7 . After round about 2 days firefox quitted responding on all machines. So used the simplest socket.io app I could find (http://stackoverflow.com/questions/9914816/what-is-an-example-of-the-simplest-possible-socket-io-example) with the latest socket.io v1.3.3 and got the same results: In 10 Minutes 3.5 MB, in 30 Minutes nearly 14 MB, in 90 Minutes more than 26 MB.

Used this files:
app.js
=====
var http = require('http'),
    fs = require('fs'),
    index = fs.readFileSync(__dirname + '/index.html');

// Send index.html to all requests
var app = http.createServer(function(req, res) {
    res.writeHead(200, {'Content-Type': 'text/html'});
    res.end(index);
});

// Socket.io server listens to our app
var io = require('socket.io').listen(app);

// Send current time to all connected clients
function sendTime() {
    io.sockets.emit('time', { time: new Date().toJSON() });
}

setInterval(sendTime, 100);

io.sockets.on('connection', function(socket) {
    socket.emit('welcome', { message: new Date().toJSON() });
    socket.on('i am client', console.log);
});

app.listen(3000);

index.html
========
```
<!doctype html>
<html>
    <head>
        <script src='//192.168.0.119:3000/socket.io/socket.io.js'></script>
        <script>
            var socket = io.connect('//192.168.0.119:3000');

            socket.on('welcome', function(data) {
				document.getElementById("start").innerHTML = data.message
                socket.emit('i am client', {data: 'foo!'});
            });
            socket.on('time', function(data) {
 				document.getElementById("end").innerHTML =  data.time;
            });
            socket.on('error', function() { console.error(arguments) });
            socket.on('message', function() { console.log(arguments) });
        </script>
    </head>
    <body>
		<p id='start'></p>
        <p id='end'></p>
    </body>
</html>

**Comment by manast** [comment]
Can you add the complete index.html also? I would like to debug this...

**Comment by jollek** [comment]
Sorry,

index.html
=========
<!doctype html>
<html>
<head>
<script src='//code.jquery.com/jquery-1.7.2.min.js'></script>
<script src='//localhost:3000/socket.io/socket.io.js'></script>
<script>
var socket = io.connect('//localhost:3000');socket.on('welcome', function(data) {
$('#messages').append('<li>' + data.message + '</li>');socket.emit('i am client', {data: 'foo!'});
});
socket.on('time', function(data) {
console.log(data);
$('#messages').append('<li>' + data.time + '</li>');
});
socket.on('error', function() { console.error(arguments) });
socket.on('message', function() { console.log(arguments) });
</script>
</head>
<body>
<ul id='messages'></ul>
</body>
</html>

**Comment by manast** [comment]
For that particular case the memory on Chrome 40 and socket.io 1.3.3 is < 10Mb, and I cannot find any obvious leaks at least.

**Comment by jollek** [comment]
Maybe its because I used Firefox 34.0.5. But I don't think so. Maybe its when more than 1 machine are used. Maybe it needs time. After nearly exact 1 day the used RAM in taskmanager  decreases by round about 50 MB from 131 to 81 MB. And then grows to more than 131MB and falls to 83MB and so on (Don't know the exact values).
On 3 of my test machines the game is over.  On  the other I started with ws the same test later .
In the case you would not believe it, I made screenshots:
![firefox stopped pc1](https://cloud.githubusercontent.com/assets/10977361/6189733/29ad3616-b39d-11e4-816e-b03324c8108e.PNG)
![firefox stopped pc2](https://cloud.githubusercontent.com/assets/10977361/6189757/5482c266-b39d-11e4-8da8-d5c9dc8ad851.PNG)
![firefox stopped pc3](https://cloud.githubusercontent.com/assets/10977361/6189760/5c201bea-b39d-11e4-9c21-5222c4ad118f.PNG)


.

**Comment by manast** [comment]
What I meant is that I cannot find obvious leaks on Chrome 40. I made memory snapshots and analize them, and I could not find anything suspicious. You could also debug a bit more in firefox, just checking the task manager is not going to tell you much, it could be a leak in Firefox for all we know...

**Comment by jollek** [comment]
> You could also debug a bit more in firefox.
What are your suggestions?

**Comment by manast** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Performance/about:memory

**Comment by jollek** [comment]
Thank you for now. I'll check it.

**Comment by jollek** [comment]
We can bring it to an end. Neither socket.io nor my app caused firefox quitting responding. It was firefox's setting ""firefox will remember history". After I gave it a last try with "firefox will never remember history" it is now 2 weeks running. Interisting is the memory consumption compared with chromium. 5 Days after start chromium reached its peak working set with 80272k and 71240k and is unchanged since 7 days. Firefox's peak working set is yet increasing and is now 197176k. 
Pagefaults after 2 weeks: firefox 343.373.099 and chromium 2.976.538 and 127.783.
Looks like I have to switch my clients over to chromium.
@manast: thanx for your collaboration.

cu

**Comment by nkzawa** [comment]
It looks the problem has been solved.
