### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by liviez** [Automattic/socket.io-client#820]
Hi,

I'm developing a web app with both client and server side using node and socket.io-client 1.3.4. When I run the server, node throws an exception saying 

```javascript
var isAndroid = navigator.userAgent.match(/Android/i);
                ^
ReferenceError: navigator is not defined
```

If I have a look the generated client, I can see that it always assumes a browser (client) is running the code, so no 

```javascript
'undefined' != typeof navigator
```
condition is done and the require('socket.io.js') in the server side fails.

I guess this is done by browserify, which I think is 4 major versions behind the latest one.

I've been trying to do the fix myself but I want to make sure there is there no fix or workaround for this already?

Thank you very much!

**Comment by Nibbler999** [comment]
You are supposed to `require('socket.io-client')`

https://github.com/Automattic/socket.io-client#nodejs-server-side-usage

**Comment by liviez** [comment]
Thank you!

The problem was basically an odd legacy way of installing the library with bower. Apparently it was not done through npm. Since bower adds the complete code base of the library in components folder, we were requiring just the autogenerated client, Therefore, it was complaining.

Now it doesn't. Thank you very much. I completely missed that part of the doc.

**Comment by nkzawa** [comment]
Seems solved. @Nibbler999 thank you for your help :smile:

**Comment by m-a-r-c-e-l-i-n-o** [comment]
What if you are doing `import Server from 'socket.io-client'`, this error is still present. Any workarounds?
