### ISSUE TITLE
Next method

### ISSUE THREAD

**Issue by dimitrilahaye** [Automattic/socket.io-client#823]
Hello there !
Just to know what does the next method ?
Thanks for the answer ! ;)

**Comment by nkzawa** [comment]
What do you mean next method? There is no such method on socket.io.

**Comment by dimitrilahaye** [comment]
eg.
```javascript
io.of('/test').use(function(socket, next){
  console.log("Authenticating...")
  next();
});
```

**Comment by peteruithoven** [comment]
I'm afraid, untill the docs are improved you'll need to read the source to figure that out. Here's the function that you receive as *next*. 
https://github.com/Automattic/socket.io/blob/master/lib/index.js#L121

**Comment by defunctzombie** [comment]
The `next` method is a function provided to you as an argument so you can indicate to socket.io when your function call is complete. This is done because your function maybe choose to do async things which will require a callback.
