### ISSUE TITLE
Event not emitting on page load

### ISSUE THREAD

**Issue by camj256** [Automattic/socket.io-client#830]
On page load I connect to socket.io then emit some events.

For example, one of those events may grab a list of Vehicle Makes or Models. 

About 75% of the time (it seems random) if I connect then do socket.emit('req-vehicles') the server never sees the event. However, if I setup a 2 second timeout before emitting any requests it will work everytime. 

Any clue why this is? If any more info is needed let me know!

Thanks,

Cameron

**Comment by Pas92** [comment]
I am also experiencing this issue.

**Comment by camj256** [comment]
Anyone find anything on this?

**Comment by nkzawa** [comment]
Can you post a code example which we can reproduce the issue?

**Comment by camj256** [comment]
Just something like:

var socket = io.connect();

$(document).ready(function(){
    socket.emit('req-vehicles');
});

The server will never see the req-vehicles.

If I add a timeout of two second the server will see it. Its odd because this didn't used to happen. Not sure what it is. I didn't spend a ton of time debugging. The connection may not have been made yet?

**Comment by nkzawa** [comment]
What version of socket.io-client do you use? On recent versions of socket.io, messages emitted before `connect` event will be buffered and sent when the connection is actually established.

**Comment by camj256** [comment]
Is the socket connection async? Is there a callback?

I upgrade often. Every couple of months. I'm on 1.3.5 right now.

**Comment by nkzawa** [comment]
I tried to reproduce the issue, but it worked fine for me. 

Connection happens async. You can listen `connect` event to know when the connection actually established.

**Comment by camj256** [comment]
On this particular app a LOT is going on right on load so that could be it.

Can you just do?

 socket.on('connect', function() { 
    console.log('connected');
 });

I'll close it if that is the case. I thought I looked for something like this a year or so ago and never found it.

**Comment by nkzawa** [comment]
yep, you can `socket.on('connect', function(){})`. Anyway it sounds a bug if there is data loss.
Please inform us if you could find how to reproduce this.

**Comment by camj256** [comment]
I'm probably just firing off events before its connected. Thanks.
