### ISSUE TITLE
Compile issues windows node 0.12.2/0.12.0

### ISSUE THREAD

**Issue by Karnith** [Automattic/socket.io-client#838]
except for engine.io, all of socket.io is failing compile on win 8.1. (engine.io-client, socket.io-client, socket.io)

the fix was to reference all the correct modules in package.json. I tested in forks.

**Comment by Karnith** [comment]
2 months and still nothing from maintainers....

**Comment by rauchg** [comment]
This is already addressed in `master`. Working on a release!
