### ISSUE TITLE
Not able to create simultaneous multiple Socket Connections

### ISSUE THREAD

**Issue by sabapk** [Automattic/socket.io-client#850]
We are trying to create multiple socket connections simultaneously from socket.io-client to backend Socket server(implemented using, https://github.com/miguelgrinberg/Flask-SocketIO). But we are unable to achieve this, as Socket connection is successful only for first connection, and we are not able to have any further simultaneous socket connections until the first one disconnects. The other socket connections are just Queueing up. So, is this the expected behaviour ? 

Also when we tried by running on separate node shells, we were able to establish simultaneous socket connections. But when trying to open multiple socket connections from one node shell, the above explained behaviour occurs.
So can we get the multiple socket connections simultaneously by changing some parameters?

Attaching diagram for better understanding.

![node server](https://cloud.githubusercontent.com/assets/3510754/8081422/350601d6-0f92-11e5-85c4-2e63ce8cef10.png)

**Comment by nkzawa** [comment]
Can you post your client code? Did you enable the `forceNew` option to create a new connection?

**Comment by sabapk** [comment]
var url, proxySocket;
      url = "http://socket-server.com:80/namespace";   // This is not the actual url.
      var config = {
             'forceNew': true
      };
      proxySocket = socketClient.connect(url, config);
      proxySocket.on('connect', handleConnection);


When first time socket connection is tried, the connect event is fired and the `handleConnection` callback is called. But later the event doesn't get fired and thus the callback is not executed.

**Comment by nkzawa** [comment]
The code looks good to me, and as far as I tried with Node.js server, it works fine too.
I think it's the problem of Flask-SocketIO.

**Comment by sabapk** [comment]
As understood by running different scenarios, the opening of socket connection is getting queued up. From second request onwards, the request to open connection is not reaching the server. Only after the first socket connection disconnects, the further socket (waiting in queue) connects.

Also, when I run from two different node shells(i.e. two separate node processes), simultaneous two socket connections are getting opened. But from a single node process, only one connection in possible.

**Comment by sabapk** [comment]
The version used of socket.io-client is 0.9.16.

**Comment by nkzawa** [comment]
Options for 0.9 are a bit different from 1.x. Did you try `force new connection` options instead of `forceNew`?

**Comment by sabapk** [comment]
Can you provide a little more details of this option?

**Comment by nkzawa** [comment]
Unfortunately, there is no doc for the option, but it's basically the same with `forceNew` option which always creates a new connection.

see https://github.com/Automattic/socket.io-client/blob/0.9/lib/io.js#L192

```
io.connect(url, { 'force new connection': true });
```

**Comment by sabapk** [comment]
Thanks, this solved my issue.
